# Generated by Django 4.1.1 on 2023-05-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Главное меню',
                'verbose_name_plural': 'Главное меню',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('text', models.TextField()),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('text', models.TextField()),
                ('promotion', models.BooleanField(default=False)),
                ('promotion_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Меню категорий',
                'verbose_name_plural': 'Меню категорий',
            },
        ),
    ]
