# Generated by Django 4.1.1 on 2023-05-24 07:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публиковать'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='name_kz',
            field=models.CharField(max_length=200, null=True, verbose_name='Название меню каз'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='text_kz',
            field=models.TextField(null=True, verbose_name='Описание каз'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 24, 7, 35, 59, 569775, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публиковать'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_kz',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование товара каз'),
        ),
        migrations.AddField(
            model_name='products',
            name='promotion_price',
            field=models.IntegerField(default=0, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='products',
            name='text_kz',
            field=models.TextField(null=True, verbose_name='Описание каз'),
        ),
        migrations.AddField(
            model_name='products',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 24, 7, 36, 11, 88728, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публиковать'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='name_kz',
            field=models.CharField(max_length=200, null=True, verbose_name='Название меню каз'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='promotion_text_kaz',
            field=models.TextField(null=True, verbose_name='Текст акции каз'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='text_kz',
            field=models.TextField(null=True, verbose_name='Описание каз'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submenu',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название меню'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название меню'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='promotion',
            field=models.BooleanField(default=False, verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='promotion_text',
            field=models.TextField(verbose_name='Текст акции'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
