# Generated by Django 4.1.1 on 2023-05-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mainmenu_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название меню')),
                ('name_kz', models.CharField(max_length=200, verbose_name='Название меню каз')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликованный')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('text', models.TextField(verbose_name='Описание')),
                ('text_kz', models.TextField(verbose_name='Описание каз')),
                ('promotion', models.BooleanField(default=False, verbose_name='Акция')),
                ('promotion_text', models.TextField(verbose_name='Текст акции')),
                ('promotion_text_kaz', models.TextField(verbose_name='Текст акции каз')),
            ],
            options={
                'verbose_name': 'Меню категорий',
                'verbose_name_plural': 'Меню категорий',
            },
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'verbose_name': 'Меню подкатегорий', 'verbose_name_plural': 'Меню подкатегорий'},
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='text_kz',
            field=models.TextField(verbose_name='Описание каз'),
        ),
        migrations.AlterField(
            model_name='products',
            name='text_kz',
            field=models.TextField(verbose_name='Описание каз'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='name_kz',
            field=models.CharField(max_length=200, verbose_name='Название меню каз'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='promotion_text_kaz',
            field=models.TextField(verbose_name='Текст акции каз'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='text_kz',
            field=models.TextField(verbose_name='Описание каз'),
        ),
    ]
