# Generated by Django 4.1.1 on 2023-05-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categorymenu_alter_submenu_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryMenu',
        ),
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'verbose_name': 'главное меню', 'verbose_name_plural': 'Главное меню'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'verbose_name': 'меню категорий', 'verbose_name_plural': 'Меню категорий'},
        ),
        migrations.AddField(
            model_name='submenu',
            name='category_id',
            field=models.CharField(choices=[('B', 'Черный'), ('C', 'Цветной'), ('I', 'Изделие'), ('N', 'Нержавеющий')], default='B', max_length=1),
        ),
    ]
