# Generated by Django 4.1.1 on 2023-05-24 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_categorymenu_alter_mainmenu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='name_description',
            field=models.CharField(max_length=200, null=True, verbose_name='Подтекст'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='name_description_kz',
            field=models.CharField(max_length=200, null=True, verbose_name='Подтекст каз'),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/%Y/%m/%d/', verbose_name='Изображение товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submenu',
            name='name_description',
            field=models.CharField(max_length=200, null=True, verbose_name='Подтекст'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='name_description_kz',
            field=models.CharField(max_length=200, null=True, verbose_name='Подтекст каз'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='text',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='text_kz',
            field=models.TextField(null=True, verbose_name='Описание каз'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='category_id',
            field=models.CharField(choices=[('B', 'Черный'), ('C', 'Цветной'), ('I', 'Изделие'), ('N', 'Нержавеющий')], default='B', max_length=1, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='promotion_text',
            field=models.TextField(null=True, verbose_name='Текст акции'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='promotion_text_kaz',
            field=models.TextField(null=True, verbose_name='Текст акции каз'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='text',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='text_kz',
            field=models.TextField(null=True, verbose_name='Описание каз'),
        ),
    ]
