# Generated by Django 4.1.1 on 2023-05-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mainmenu_name_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
