# Generated by Django 4.1.1 on 2023-05-24 16:35

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='page_editor',
            field=tinymce.models.HTMLField(default=None, verbose_name='Изменения страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='page_editor_kz',
            field=tinymce.models.HTMLField(default=None, verbose_name='Изменения страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='page_editor',
            field=tinymce.models.HTMLField(default=None, verbose_name='Изменения страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='page_editor_kz',
            field=tinymce.models.HTMLField(default=None, verbose_name='Изменения страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submenu',
            name='page_editor',
            field=tinymce.models.HTMLField(default=None, verbose_name='Изменения страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submenu',
            name='page_editor_kz',
            field=tinymce.models.HTMLField(default=None, verbose_name='Изменения страницы'),
            preserve_default=False,
        ),
    ]
