# Generated by Django 4.1.1 on 2023-05-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_mainmenu_page_editor_mainmenu_page_editor_kz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='page_editor',
            field=models.TextField(verbose_name='Изменения страницы'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='page_editor_kz',
            field=models.TextField(verbose_name='Изменения страницы каз'),
        ),
        migrations.AlterField(
            model_name='products',
            name='page_editor',
            field=models.TextField(verbose_name='Изменения страницы'),
        ),
        migrations.AlterField(
            model_name='products',
            name='page_editor_kz',
            field=models.TextField(verbose_name='Изменения страницы каз'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='page_editor',
            field=models.TextField(verbose_name='Изменения страницы'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='page_editor_kz',
            field=models.TextField(verbose_name='Изменения страницы каз'),
        ),
    ]
