# Generated by Django 4.1.1 on 2023-05-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_mainmenu_page_editor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('company_title', models.CharField(max_length=200, verbose_name='Краткое описание компании')),
                ('company_title_kz', models.CharField(max_length=200, verbose_name='Краткое описание компании каз')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликованный')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('phone_1', models.IntegerField(verbose_name='Номер телефона')),
                ('phone_2', models.IntegerField(verbose_name='Номер телефона')),
                ('phone_3', models.IntegerField(verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=2000, verbose_name='Адрес компании')),
                ('e_address', models.EmailField(max_length=500, verbose_name='Email адрес компании')),
            ],
            options={
                'verbose_name': 'настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='page_editor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='page_editor_kz',
            field=models.TextField(),
        ),
    ]
