# Generated by Django 4.1.1 on 2023-05-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_settings_alter_mainmenu_page_editor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='static/', verbose_name='Logo компании'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='static/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
