# Generated by Django 4.1.1 on 2023-05-25 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_settings_company_logo_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='work_time',
            field=models.CharField(default=None, max_length=200, verbose_name='График работы'),
            preserve_default=False,
        ),
    ]
