# Generated by Django 4.1.1 on 2023-05-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_settings_work_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'настройку', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AddField(
            model_name='settings',
            name='instagram',
            field=models.CharField(max_length=200, null=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AddField(
            model_name='settings',
            name='telegram',
            field=models.CharField(max_length=200, null=True, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='company_title',
            field=models.CharField(max_length=200, null=True, verbose_name='Краткое описание компании'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='company_title_kz',
            field=models.CharField(max_length=200, null=True, verbose_name='Краткое описание компании каз'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(max_length=200, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone_1',
            field=models.CharField(max_length=200, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone_2',
            field=models.CharField(max_length=200, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone_3',
            field=models.CharField(max_length=200, null=True, verbose_name='Номер телефона'),
        ),
    ]
