# Generated by Django 4.1.1 on 2023-05-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_settings_options_settings_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='test_editor',
            field=models.TextField(blank=True, null=True, verbose_name='Тестовый для проверки на сайте'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='name_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подтекст'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='name_description_kz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подтекст каз'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='name_kz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название меню каз'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='page_editor',
            field=models.TextField(blank=True, verbose_name='Изменения страницы'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='page_editor_kz',
            field=models.TextField(blank=True, verbose_name='Изменения страницы каз'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='text_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание каз'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_kz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование товара каз'),
        ),
        migrations.AlterField(
            model_name='products',
            name='page_editor',
            field=models.TextField(blank=True, verbose_name='Изменения страницы'),
        ),
        migrations.AlterField(
            model_name='products',
            name='page_editor_kz',
            field=models.TextField(blank=True, verbose_name='Изменения страницы каз'),
        ),
        migrations.AlterField(
            model_name='products',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='text_kz',
            field=models.TextField(blank=True, verbose_name='Описание каз'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='company_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Краткое описание компании'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='company_title_kz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Краткое описание компании каз'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='name_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подтекст'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='name_description_kz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подтекст каз'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='name_kz',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название меню каз'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='page_editor',
            field=models.TextField(blank=True, verbose_name='Изменения страницы'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='page_editor_kz',
            field=models.TextField(blank=True, verbose_name='Изменения страницы каз'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='promotion_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст акции'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='promotion_text_kaz',
            field=models.TextField(blank=True, null=True, verbose_name='Текст акции каз'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='text_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание каз'),
        ),
    ]
