# Generated by Django 4.1.1 on 2023-05-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmenu',
            old_name='page_editor',
            new_name='page_html_text',
        ),
        migrations.RenameField(
            model_name='mainmenu',
            old_name='page_editor_kz',
            new_name='page_html_text_kz',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='page_editor',
            new_name='page_html_text',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='page_editor_kz',
            new_name='page_html_text_kz',
        ),
        migrations.RenameField(
            model_name='submenu',
            old_name='page_editor',
            new_name='page_html_text',
        ),
        migrations.RenameField(
            model_name='submenu',
            old_name='page_editor_kz',
            new_name='page_html_text_kz',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/', verbose_name='Загрузить изображение'),
        ),
    ]
