# Generated by Django 4.1.1 on 2023-05-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_page_editor_mainmenu_page_html_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmenu',
            name='page_html_text',
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='page_html_text_kz',
        ),
        migrations.RemoveField(
            model_name='products',
            name='page_html_text',
        ),
        migrations.RemoveField(
            model_name='products',
            name='page_html_text_kz',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='page_html_text',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='page_html_text_kz',
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='page_html',
            field=models.TextField(blank=True, verbose_name='Изменения страницы'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='page_html_kz',
            field=models.TextField(blank=True, verbose_name='Изменения страницы каз'),
        ),
        migrations.AddField(
            model_name='products',
            name='page_html',
            field=models.TextField(blank=True, verbose_name='Изменения страницы'),
        ),
        migrations.AddField(
            model_name='products',
            name='page_html_kz',
            field=models.TextField(blank=True, verbose_name='Изменения страницы каз'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='page_html',
            field=models.TextField(blank=True, verbose_name='Изменения страницы'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='page_html_kz',
            field=models.TextField(blank=True, verbose_name='Изменения страницы каз'),
        ),
    ]
