# Generated by Django 4.1.1 on 2023-05-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_mainmenu_page_html_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='title_kaz',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок страницы каз'),
        ),
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='products',
            name='title_kaz',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок страницы каз'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='title_kaz',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок страницы каз'),
        ),
    ]
