# Generated by Django 4.1.1 on 2023-05-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_mainmenu_title_mainmenu_title_kaz_products_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description SEO'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='meta_description_kaz',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description SEO kaz'),
        ),
        migrations.AddField(
            model_name='products',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description SEO'),
        ),
        migrations.AddField(
            model_name='products',
            name='meta_description_kaz',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description SEO kaz'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description SEO'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='meta_description_kaz',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description SEO kaz'),
        ),
    ]
