# Generated by Django 4.1.1 on 2023-05-26 06:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_mainmenu_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='category_id',
        ),
        migrations.AddField(
            model_name='submenu',
            name='main_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mainmenu'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubCategoryMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Заголовок страницы')),
                ('title_kaz', models.CharField(max_length=200, null=True, verbose_name='Заголовок страницы каз')),
                ('name', models.CharField(max_length=200, verbose_name='Название меню')),
                ('name_kz', models.CharField(blank=True, max_length=200, verbose_name='Название меню каз')),
                ('name_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подтекст')),
                ('name_description_kz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подтекст каз')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликованный')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('page_html', models.TextField(blank=True, verbose_name='Изменения страницы')),
                ('page_html_kz', models.TextField(blank=True, verbose_name='Изменения страницы каз')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text_kz', models.TextField(blank=True, null=True, verbose_name='Описание каз')),
                ('promotion', models.BooleanField(default=False, verbose_name='Акция')),
                ('promotion_text', models.TextField(blank=True, null=True, verbose_name='Текст акции')),
                ('promotion_text_kaz', models.TextField(blank=True, null=True, verbose_name='Текст акции каз')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description SEO')),
                ('meta_description_kaz', models.TextField(blank=True, null=True, verbose_name='Meta Description SEO kaz')),
                ('main_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.submenu')),
            ],
            options={
                'verbose_name': 'меню категорий',
                'verbose_name_plural': 'Меню категорий',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='main_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subcategorymenu'),
            preserve_default=False,
        ),
    ]
