# Generated by Django 4.1.1 on 2023-05-26 06:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_submenu_category_id_submenu_main_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='main_menu',
            field=models.ForeignKey(null = True, on_delete=django.db.models.deletion.CASCADE, to='main.subcategorymenu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submenu',
            name='main_menu',
            field=models.ForeignKey(null = True, on_delete=django.db.models.deletion.CASCADE, to='main.mainmenu'),
            preserve_default=False,
        ),
    ]
