# Generated by Django 4.1.1 on 2023-05-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_subcategorymenu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/%Y/%m/%d/', verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
