# Generated by Django 4.1.1 on 2023-05-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_submenu_image_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/%Y/%m/%d/', verbose_name='Изображение категории'),
        ),
    ]
